! DO NOT EDIT THIS FILE.
! This file was automatically generated by arcpp.
! Edit the original file, libcol.arc, instead.
BLACK .equ 0 
 _BLACK0 .equ 0
BLUE .equ 3 
 _BLUE0 .equ 3
BROWN .equ 164 
 _BROWN0 .equ 164
CYAN .equ 191 
 _CYAN0 .equ 191
GREEN .equ 28 
 _GREEN0 .equ 28
MAROON .equ 32 
 _MAROON0 .equ 32
NAVY .equ 1 
 _NAVY0 .equ 1
OLIVE .equ 132 
 _OLIVE0 .equ 132
ORANGE .equ 236 
 _ORANGE0 .equ 236
PINK .equ 227 
 _PINK0 .equ 227
RED .equ 224 
 _RED0 .equ 224
WHITE .equ 255 
 _WHITE0 .equ 255
YELLOW .equ 252 
 _YELLOW0 .equ 252
